### ISSUE TITLE
【依頼】ProtoSpace挙動確認	

### ISSUE THREAD

**Issue by Aya-Nori** [Aya-Nori/protospace#1]
# URL	
https://protospace-39485.onrender.com/

カリキュラムProtospaceの実装を行いましたので、確認をお願いします。

**Comment by motomuun** [comment]
@Aya-Nori さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**プロトタイプ一覧表示機能**

- [ ] **ログイン・ログアウトの状態に関わらず、一覧表示されている画像およびプロトタイプ名をクリックすると、該当するプロトタイプの詳細ページへ遷移すること**
プロトタイプ名をクリックしても、プロトタイプの詳細ページへ遷移できません。遷移できるように修正をお願いします。

**ユーザー詳細機能**

- [ ] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移すること**
コメント投稿者名をクリックするとトップページに遷移します。コメント投稿者のユーザー詳細ページへ遷移するように修正をお願いします。



修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
修正内容が反映されていることが確認できましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by Aya-Nori** [comment]
上記二点の修正を行い、本番環境で動作確認を行いましたので、再確認をお願いいたします。

**Comment by shodai-ito** [comment]
@Aya-Nori さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

※中央の要素が大きいと、レイアウトが大きく崩れます。
<img width="1091" alt="スクリーンショット 2023-08-30 9 34 01" src="https://github.com/Aya-Nori/protospace-39485/assets/62537107/f87236b5-7128-4738-abb6-75259460588a">
<img width="1194" alt="スクリーンショット 2023-08-30 9 34 16" src="https://github.com/Aya-Nori/protospace-39485/assets/62537107/2a8ed930-b508-4240-835c-8445947c4ec4">
こちらも修正いただくと、よりユーザー体験がよくなるかと思われます。
こちらは必須ではないため、修正の報告は不要です。

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください。
